### ISSUE TITLE
Intermittent Client Crashing When Breaking Blocks with Spelunking Potion Active

### ISSUE THREAD

**Issue by bardelan** [Lex305/Spelunker#15]
Description in title.  Issue occurs when breaking an ore block with the Spelunking effect active, or when breaking another block to reveal the ore block behind it.

We are using Spelunker in a custom mod pack on a private multiplayer server running Minecraft v 1.19.2.  Latest crash log attached, but the thrown exception and stack trace are identical across four client crashes.  

[crash-2023-01-31_15.05.20-client.txt](https://github.com/Leximon/Spelunker/files/10550530/crash-2023-01-31_15.05.20-client.txt)

**Comment by EvionFox** [comment]
Server host here! I'm linking a gist paste of the config (spelunker.hjson) as well, since we added modded ores: https://gist.github.com/EvionFox/608d640c5d615771cf181abe82e218bf

**Comment by Rasmion** [comment]
Please try to replicate the crash with the [latest build](https://github.com/Leximon/Spelunker/suites/10697808464/artifacts/535619783).

**Comment by EvionFox** [comment]
Thank you for the fast response. Unfortunately those new files are causing a crash on startup for the game. I made sure to remove the 1.5.1 spelunker file from my mods at the time.

When using just the 1.5.2.jar: 
[crash-2023-01-31_16.31.24-client.txt](https://github.com/Leximon/Spelunker/files/10551668/crash-2023-01-31_16.31.24-client.txt)

When using the 1.5.2-sources.jar:
[crash-2023-01-31_16.35.00-client.txt](https://github.com/Leximon/Spelunker/files/10551670/crash-2023-01-31_16.35.00-client.txt)

When using both of the provided jars:
[crash-2023-01-31_16.39.05-client.txt](https://github.com/Leximon/Spelunker/files/10551678/crash-2023-01-31_16.39.05-client.txt)

**Comment by Leximon** [comment]
Whoops, this build was meant for 1.19.3. Sorry about that.
Try it again with [this build](https://github.com/Leximon/Spelunker/suites/10716294863/artifacts/536989825)

**Comment by EvionFox** [comment]
Thank you!
The test is successful with the new build - Having tested it both on a solo world and on the dedicated server, I did not encounter the crash.

However, it does seem that the mod now suppresses the "Vein Mining" enchantment functionality. I tested harvesting the same ores both with the mods and without, and with the mod it limited ores to one block at a time. Without, the ores all broke together as normal. But vein mining functioned as normal on non-ore blocks.

Also, I don't know if it's intentional, but the ore blocks leave a ghost outline of where they were located after being mined. Basically, the spelunker highlights remain for all of the ores originally seen until the potion effect wears off. If this is necessary for functionality, that's fine, just wanted to note it.

**Comment by Rasmion** [comment]
It looks like there is an incompatibility between Spelunker and another mod. Spelunker + [Vein Mining](https://www.curseforge.com/minecraft/mc-mods/vein-mining-fabric/download/4280463) works and no ghost outlines are left behind. Could you provide us with a modlist?

https://www.youtube.com/watch?v=D0kurPjbcm0

**Comment by EvionFox** [comment]
Thank you, here is the mod list from the pack:

[modlist.txt](https://github.com/Leximon/Spelunker/files/10561890/modlist.txt)

I'm attempting to do some trial-and-error tests to narrow down the culprit right now.
I forgot to include a link to the Modpack in case that would help: https://www.curseforge.com/minecraft/modpacks/lynxsmp

**Comment by EvionFox** [comment]
After some more testing - the process all works properly in a solo world without the ghosting or vein mining weirdness. However, when used on a dedicated server, it's still having this issue.

When mining, this error is popping up in the server log:
`[22:30:06] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2846@2e71342e, suppressing error
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:?]
        at net.minecraft.class_1937.mdcb9a36$lambda$spelunkerUpdateBlock$0$3(class_1937.java:13606) ~[server-intermediary.jar:?]
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) ~[?:?]
        at net.minecraft.class_1937.spelunkerUpdateBlock(class_1937.java:13603) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.handler$hik001$onBlockChangedInject(class_3218.java:26707) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_19282(class_3218.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_30092(class_1937.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_8652(class_1937.java:206) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_8650(class_1937.java:281) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14266(class_3225.java:257) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_21717(class_3225.java:228) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14263(class_3225.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12066(class_3244.java:1092) ~[server-intermediary.jar:?]
        at net.minecraft.class_2846.method_12361(class_2846.java:42) ~[server-intermediary.jar:?]
        at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$cke000$catchExceptionsDuringNetworking(MinecraftServer.java:9814) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bmo000$modifiedRunLoop(MinecraftServer.java:7894) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by Rasmion** [comment]
Everything is fixed in the next commit, closing this issue. If you find more bugs, please open a seperate issue!
The new jar will be generated with the build and you can download them there. The curseforge release will be delayed a bit, because we are changing a few things regarding publishing.
Thanks for reporting!

**Comment by Rasmion** [comment]
Here you can download the [latest build](https://github.com/Leximon/Spelunker/suites/10742687844/artifacts/538953187) for 1.19.2.

**Comment by ConqAra** [comment]
Is there a build for 1.18.2 available?

**Comment by ConqAra** [comment]
> Here you can download the [latest build](https://github.com/Leximon/Spelunker/suites/10742687844/artifacts/538953187) for 1.19.2.

@Rasmion 
Is there a build for 1.18.2 available? Getting that same error
